### ISSUE TITLE
How do I create the latest reference?

### ISSUE THREAD

**Issue by xuxingyubio** [YingZhou001/Immuannot#5]
Hi Ying,
The version of IMGT has been updated, how should I create the latest reference?

**Comment by YingZhou001** [comment]
Updated, it can be downloaded from https://zenodo.org/records/10948964

**Comment by xuxingyubio** [comment]
Thank you so much for your immediate updates.

**Comment by xuxingyubio** [comment]
When I use the latest version of the reference, the generated gtf is empty. The error is as follows:

<msg> loading paf records
<msg> loading contig seq
<msg> searching template:
Warning, CDS seq may be incomplete
query seq:HLA-F*01:01:01:20
target seq:110
Warning, CDS seq may be incomplete
query seq:HLA-F*01:01:01:20
target seq:110
Warning, CDS seq may be incomplete
query seq:HLA-DPB2*03:01:01:01
target seq:117
Traceback (most recent call last):
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 417, in <module>
    out = searchTemplatePGPC(pafDA, ctgname, qctgseqs)
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 319, in searchTemplatePGPC
    right = s2[-2] + s2[-1]
IndexError: string index out of range

When I use the older version, there are also errors, but the output is not empty. The error is as follows:

<msg> loading paf records
<msg> loading contig seq
<msg> searching template:
Warning, CDS seq may be incomplete
query seq:HLA-F*01:01:01:20
target seq:110
Warning, CDS seq may be incomplete
query seq:HLA-F*01:01:01:20
target seq:110
Warning, CDS seq may be incomplete
query seq:HLA-DPB2*03:01:01:01
target seq:117
Traceback (most recent call last):
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 417, in <module>
    out = searchTemplatePGPC(pafDA, ctgname, qctgseqs)
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 319, in searchTemplatePGPC
    right = s2[-2] + s2[-1]
IndexError: string index out of range

What is the reason for this?

**Comment by xuxingyubio** [comment]
The file is as follows:
[mm2.ipd.gen.paf.gz](https://github.com/YingZhou001/Immuannot/files/14985488/mm2.ipd.gen.paf.gz)

**Comment by YingZhou001** [comment]
I can generate the annotation gtf with the paf you shared with me, see
[tmp.ipd.gtf.gz](https://github.com/YingZhou001/Immuannot/files/14985798/tmp.ipd.gtf.gz)
I am wondering if there is any special character like spaces in your contig id? Otherwise I cannot see any problem.

**Comment by xuxingyubio** [comment]
My contig id is as follows:
>103 edges=4206..4770 left=3549 right=1867 ver=1.10 style=4
>106 edges=4552..5001 left=4112 right=4208 ver=1.10 style=4

But when I use Data-2023Oct27, it can generate the annotation gtf.

**Comment by YingZhou001** [comment]
I would suggest you to use underscore '_' to replace spaces in the contig name. As you showed before, using Data-2023Oct27 still had errors.

**Comment by xuxingyubio** [comment]
I tried a different fasta file, contig id is as follows:
>ptg000001l
>ptg000002l

It still reports an error:
Traceback (most recent call last):
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 418, in <module>
    out = searchTemplatePGPC(pafDA, ctgname, qctgseqs)
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 183, in searchTemplatePGPC
    alleles, alleleda = readAllele(allelefile)
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 35, in readAllele
    k, v = x.split('=')
ValueError: too many values to unpack (expected 2)

The resulting gtf file has only the annotation information of the C4.

**Comment by xuxingyubio** [comment]
The fasta file is as follows:
[NA12878.fasta.gz](https://github.com/YingZhou001/Immuannot/files/14986051/NA12878.fasta.gz)

**Comment by YingZhou001** [comment]
I can also run the NA12878.fasta.gz, see my output:
[out.gtf.gz](https://github.com/YingZhou001/Immuannot/files/15003745/out.gtf.gz)
[out.tar.gz](https://github.com/YingZhou001/Immuannot/files/15003747/out.tar.gz)
Could you compare these with yours and let me know which one is different ?

**Comment by xuxingyubio** [comment]
When my `refdir` is set to `Data-2024Feb02`, I still get an error, and the generated files are as follows:
[2024_out.gtf.gz](https://github.com/YingZhou001/Immuannot/files/15005540/2024_out.gtf.gz)
[2024_out.tar.gz](https://github.com/YingZhou001/Immuannot/files/15005541/2024_out.tar.gz)

However, when my `refdir` is set to `Data-2023Oct27`, it runs successfully:

[2023_out.gtf.gz](https://github.com/YingZhou001/Immuannot/files/15005557/2023_out.gtf.gz)
[2023_out.tar.gz](https://github.com/YingZhou001/Immuannot/files/15005558/2023_out.tar.gz)

Is there any inconsistency between `Data-2024Feb02` and `Data-2023Oct27`?

**Comment by xuxingyubio** [comment]
I have successfully run it now. I'm not sure why the last line of the provided ref in Data-2024Feb02/alleles.csv.gz has some format issues. After adjusting it, it can run properly.

**Comment by xuxingyubio** [comment]
When I tried other samples, most of them ran successfully, but I encountered the following error in some samples:
<msg> searching template:
Traceback (most recent call last):
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 417, in <module>
    out = searchTemplatePGPC(pafDA, ctgname, qctgseqs)
  File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 319, in searchTemplatePGPC
    right = s2[-2] + s2[-1]

**Comment by YingZhou001** [comment]
> I have successfully run it now. I'm not sure why the last line of the provided ref in Data-2024Feb02/alleles.csv.gz has some format issues. After adjusting it, it can run properly.

Can you give me some details, otherwise I really don't know what to do. From my side I cannot see any problem there.

**Comment by YingZhou001** [comment]
> When I tried other samples, most of them ran successfully, but I encountered the following error in some samples: searching template: Traceback (most recent call last): File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 417, in out = searchTemplatePGPC(pafDA, ctgname, qctgseqs) File "/home/users/xyxu/tools/Immuannot/scripts/searchTemplate.py", line 319, in searchTemplatePGPC right = s2[-2] + s2[-1]

Do you have any data I  can repeat this problem?

**Comment by xuxingyubio** [comment]
I'm sorry, but I cannot provide the original data. However, I can roughly locate the problem as follows:

paf:
HLA-P*02:01:01:02       2931    0       2931    +       64      1964530 847965  850720  2745    2921    60      NM:i:186        ms:i:2168       AS:i:2478       nn:i:10 tp:A:P  cm:i:277        s1:i:2673       s2:i:628        de:f:0.0040     rl:i:0  cg:Z:2160M176I595M      cs:Z::2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585

searchTemplatePGPC(pafDA, ctgname, qctgseqs):
{'allele': 'HLA-P*02:01:01:02', 'codonShift': '1', 'CDS': '462..722,1312..1587,1712..1828,2241..2273,2424..2471'}
:2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585 462..722
GGTCTCCCACCTCCAGTGGATACACAGCTGCGACCTGGACCCGGACCGGAGCCTCTTCGCGCGGGGATGAACATACCCTACGATGGCGCCAGTTACCTCGTCCTAAACCAGGAACTGCTCTCTTGGACCGCAGCGGAAAAGGCGGCTCAGATGTTTTGGAGGAGGAACATGCAGAGCTGCTCAAAACCTACCTGCCGGGAAGGTGGGCGGAGTGGCTCAGCAAAGGCCTTAAGAATGAGAAGGAGAGGCTGCAATGCGCAG
:2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585 460..724
AGGGTCTCCCACCTCCAGTGGATACACAGCTGCGACCTGGACCCGGACCGGAGCCTCTTCGCGCGGGGATGAACATACCCTACGATGGCGCCAGTTACCTCGTCCTAAACCAGGAACTGCTCTCTTGGACCGCAGCGGAAAAGGCGGCTCAGATGTTTTGGAGGAGGAACATGCAGAGCTGCTCAAAACCTACCTGCCGGGAAGGTGGGCGGAGTGGCTCAGCAAAGGCCTTAAGAATGAGAAGGAGAGGCTGCAATGCGCAGGT
{'allele': 'HLA-P*02:01:01:02', 'codonShift': '1', 'CDS': '462..722,1312..1587,1712..1828,2241..2273,2424..2471'}
:2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585 1312..1587
ATCCCCTGAAGGCACAGGTAACCCTCCACCCCATCTCCAACTATGAGGCCACGCTGAGGTGCTGGGCCCTGGGCTTCTACCCTCTGGAGATCACACTGACCCAGGAGCGGGATGGGGAGGACCAAATTCAGGATGCAGAGTTTGTGGAGACCAGACTTGCAGGGTACAGAACCTTCCAGAAGTGGGCAGCTGCAGTGGTGTCTTCTGGAGAGAAGCAGAGGTACACATGCCATGTGCAGCACGAGGGGTTGCCTGAGCCCCTCACACTAAGATGGG
:2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585 1310..1589
AGATCCCCTGAAGGCACAGGTAACCCTCCACCCCATCTCCAACTATGAGGCCACGCTGAGGTGCTGGGCCCTGGGCTTCTACCCTCTGGAGATCACACTGACCCAGGAGCGGGATGGGGAGGACCAAATTCAGGATGCAGAGTTTGTGGAGACCAGACTTGCAGGGTACAGAACCTTCCAGAAGTGGGCAGCTGCAGTGGTGTCTTCTGGAGAGAAGCAGAGGTACACATGCCATGTGCAGCACGAGGGGTTGCCTGAGCCCCTCACACTAAGATGGGGT
{'allele': 'HLA-P*02:01:01:02', 'codonShift': '1', 'CDS': '462..722,1312..1587,1712..1828,2241..2273,2424..2471'}
:2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585 1712..1828
AGCTGTCTTCCCAGCCCATCATCCCCGTTGTGGGCATCATTGCTGGCCTGGTTCTTCTAGTTGCTGTAATCACTGTAGCTGTAGTCGCTGCTGTGATGTGGAGGAATAAGATCCCAG
:2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585 1710..1830
AGAGCTGTCTTCCCAGCCCATCATCCCCGTTGTGGGCATCATTGCTGGCCTGGTTCTTCTAGTTGCTGTAATCACTGTAGCTGTAGTCGCTGCTGTGATGTGGAGGAATAAGATCCCAGGT
{'allele': 'HLA-P*02:01:01:02', 'codonShift': '1', 'CDS': '462..722,1312..1587,1712..1828,2241..2273,2424..2471'}
:2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585 2241..2273

:2160+agtcacagttctggaaactcctctaggatctcatgccctgcctcctccctggcctctcacagtttgttttctttccacagatggaaaaggaggcagttatgctcaggcttcatgtaagtgtggtaggggtgggaagagtgatccctgagatccttgggatagtgtagacaggagcc*nc*na*nt*ng*ng*ng*ng*ng*na*ng:585 2239..2275


I added print statements for `s1` and `s2` in the following code. I then found that when the error occurs, `s1` and `2` are empty.
        for cds in qcds.split(",") :
            a,b = cds.split("..")
            a = int(a)
            b = int(b)
            if b > to or a < fro:
                sys.stderr.write("Warning, CDS seq may be incomplete\n"
                         + "query seq:" + da['qstr'] + '\n'
                         + "target seq:" + da['tstr'] + '\n')
                continue
            a = a - fro
            b = b - fro
            s0 = qseq[a-1:b]
            cdsrg = str(a) + '..' + str(b)
            print(csstr,cdsrg)
            # will recover positive or the same strand diretion as qseq
            s1 = at.recoverTargetSeqFromQuery(qseq, csstr, cdsrg, da['strand'])
            print(s1)
            #sys.stderr.write('*******\n')
            cdsstr += s1
            tmprg = str(a-2) + '..' + str(b + 2)
            print(csstr,tmprg)
            s2 = at.recoverTargetSeqFromQuery(qseq, csstr, tmprg, da['strand'])
            print(s2)
            """
            #sys.stderr.write('qstr ' + da['qstr'] + '_\n')
            #sys.stderr.write('tstr ' + da['tstr'] + '_\n')
            #sys.stderr.write('cdsrg_' + cds + '_\n')
            #sys.stderr.write('cdsrg_' + cdsrg + '_\n')
            #sys.stderr.write('cs_' + csstr + '_\n')
            #sys.stderr.write('s0_' + s0 + '_\n')
            #sys.stderr.write('s1_' + s1 + '_\n')
            #sys.stderr.write('s2_' + s2 + '_\n')
            """
            left = s2[0:2]
            right = s2[-2] + s2[-1]
            intronBound += left +  ":"  + right + "_"

**Comment by YingZhou001** [comment]
Sorry to get you back late, was in traveling.

Can you please print the "qseq"? I think it could be a bug in the "recoverTargetSeqFromQuery" function.

Thanks!

**Comment by xuxingyubio** [comment]
No worries at all! I hope you had a pleasant journey.

I've printed the "qseq" for you below.

GTAATTAAATTCTGTACAGGCTCCTGGTTGCAATATACGGTAATACATTGTGCTTTGTATTGAGATGTCCTGGACTCGCACACACAAACTCAGAGCTATGAAATAAAGATACTGTAAAAATACAACAGACCAGAGTCACAGATACACAGTCTGGGAAAGTAAAACTTCACTTTGTGAGTCTAATTGCAATGCGTTTAGACATATTTATATATAATGGGGCCAAAAATCATCTCTTTTACAAATTAGATTCGTGACCATTCAGGGGCTACCAAGATTGTGCTACCCACTGTAGCACAATCGGAGACCCACGCCGAGGCTGCGGGACTCGTGGAGACCCTCGACACAAGAACCCCAGGTGCCTATACCCGATTCCATTTTCAGTTCAGGCCCAAATCCCCGGGGGATTGATCGGGGCAGAGGAGGAGCTCAGTGGCTGAGGCTGACCGCGGGCTTGGGGACAGGGTCTCCCACCTCCAGTGGATACACAGCTGCGACCTGGACCCGGACCGGAGCCTCTTCGCGCGGGGATGAACATACCCTACGATGGCGCCAGTTACCTCGTCCTAAACCAGGAACTGCTCTCTTGGACCGCAGCGGAAAAGGCGGCTCAGATGTTTTGGAGGAGGAACATGCAGAGCTGCTCAAAACCTACCTGCCGGGAAGGTGGGCGGAGTGGCTCAGCAAAGGCCTTAAGAATGAGAAGGAGAGGCTGCAATGCGCAGGTACCAGAGGCCACGGGTCGCCTCCCTGATCTCCTGCAGATATCCCTGAGCCACCTTCCAAAAGAAGGGGAGGAAAATGGGACCAACGCTAAAATATCCCTCTCCCTCTTGTCCTGAGGCAGAAGAGTCCTCCTGGGTTTCTAAATCCTATACCAGAGAGTGACTGAGGGCCCGCCCTGCACTCTGGGACAATTAACGGATGAAGTCTCTGCGGGAAAGGAGGGGAAGACAATCCCTGGAATACTGATACGCGGTACCCTTTGACCCCCCAGCAGCCTTGGGCACCAGGAATTTTCCTCTCAGGCCTTGTTCTCTGCCTCATACTCAATGTGTGTGGGGGTCTGATTCCAGCTCTTCTGAGTCCCTCGGCCTCCACTCAGGTCAGGACCAGAAATCTCTGTTTCCGCCTCAGACACTAGAACTTTCCAAGGAATAAGAGATTATCCCAGGTGCCTGTGTCCAGAATGTTGTCTGGGTTCTGTGCTCCCTTCCCCACCCCAGATGTCCCATCCATTCTCAGGATGGTCACATGGGTGCTGTGTCTCATGAGGAATGCAAAGTGCCTGAATTTTCTACCTCTTGCCCTCAGATCCCCTGAAGGCACAGGTAACCCTCCACCCCATCTCCAACTATGAGGCCACGCTGAGGTGCTGGGCCCTGGGCTTCTACCCTCTGGAGATCACACTGACCCAGGAGCGGGATGGGGAGGACCAAATTCAGGATGCAGAGTTTGTGGAGACCAGACTTGCAGGGTACAGAACCTTCCAGAAGTGGGCAGCTGCAGTGGTGTCTTCTGGAGAGAAGCAGAGGTACACATGCCATGTGCAGCACGAGGGGTTGCCTGAGCCCCTCACACTAAGATGGGGTAAGGAGACGAATGAGGGGTCATGTCTCTTCTCAGGCAAAGCAGAAGTCCTTCTGGAGCCTTTAAGCAGGGTCAGGGCTGAGGCCTGGGGGTCAGGGCCCCTCACGTTCACCTCCTTTCTTAGAGCTGTCTTCCCAGCCCATCATCCCCGTTGTGGGCATCATTGCTGGCCTGGTTCTTCTAGTTGCTGTAATCACTGTAGCTGTAGTCGCTGCTGTGATGTGGAGGAATAAGATCCCAGGTAGGAAAGGGGTGAGCTCTGAGTTTCCTTCTTCCATTGGTGGATTTCAAGCCCCAGGTAGGAGTAGGCTCATATCTTGCCTAGTTGTGAGGCACCATCTCCACACACATTTACCCTGTTCAGAGGCCCTGTCTATCAACGCTTACTCTTTTGTAAAGCACTTGTGAAAATGAAGGACAAATTTATCACCTTGATTGTGGTCATGGGAACCTGACTCCCAGCAGTCACAGGTCAGGGGAAGGTCCCTGCTGAGGACAGACCTCAGGAGGACAATTGGTCCAGCCTCAACACATCCTCTTCCCTTGGGTTTTCTGATCCTGACCTGGGTCTGTAGTCACAGTTCTGGAAACTCCTCTAGGATCTCATGCCCTGCCTCCTCCCTGGCCTCTCACAGTTTGTTTTCTTTCCACAGATGGAAAAGGAGGCAGTTATGCTCAGGCTTCATGTAAGTGTGGTAGGGGTGGGAAGAGTGATCCCTGAGATCCTTGGGATAGTGTAGACAGGAGCCCATGGGGGAGCTCAGCCACCCCAAAATTCCTCCTTTAGTCACATCACCTGTGGGCTCTGACCAGATTTTGTTTTTGTTCCACCCCAAACAGGAACAGTACCCAGGGCTCTGATGTGTCTCTCAAGGCTTGTAAAAGTGACACCTTAGAGGGCCTGAAGTGAAAGAGGAGTTGGGCAGAGGGGACACAACTAAGCTCTGGAGATTCTTTGATTTGGAATTTTTCAAGGTGTGGTGGGCTGTTCAGTGTCACAACTTACTATGACTGACCTGGATTAGTTTATGACTATGTTTTTTCTAAGATTGCCTTGTGAGGGACTGAGATGCAAGATTTGTTCATGCCTCCTCTTTGTGACATTAAGAGCCTCTGGCTTCTCTTTCTGCCAAAGGGTCTGAATGTGTCTATGTCTACAGTAACAGGTAAGAAATGGGAGACCAGCCCATCCTCATGTCCACCATGACCCCTGATATTGTTTGGATCTGTGTCCCCACCCAAATCTCATGTTCAATTGTAATCCCTAATTTTGGAGGTGGTGTCTGGTGGCAGGTGATCGGCTCATGAGGATGGATCCTTCATGAACGGTTTAGAACCATCTCT

**Comment by YingZhou001** [comment]
Thanks, I figured it out. It is likely that a whole segment been deleted in the target genome. Can you please try to modify the "searchTemplate.py" file by changing from
"
            cdsstr += s1
            tmprg = str(a-2) + '..' + str(b + 2)
            s2 = at.recoverTargetSeqFromQuery(qseq, csstr, tmprg, da['strand'])
            """
            #sys.stderr.write('qstr ' + da['qstr'] + '_\n')
            #sys.stderr.write('tstr ' + da['tstr'] + '_\n')
            #sys.stderr.write('cdsrg_' + cds + '_\n')
            #sys.stderr.write('cdsrg_' + cdsrg + '_\n')
            #sys.stderr.write('cs_' + csstr + '_\n')
            #sys.stderr.write('s0_' + s0 + '_\n')
            #sys.stderr.write('s1_' + s1 + '_\n')
            #sys.stderr.write('s2_' + s2 + '_\n')
            """
            left = s2[0:2]
            right = s2[-2] + s2[-1]
            intronBound += left +  ":"  + right + "_"

"

into

"
            if s1 :
                cdsstr += s1
                tmprg = str(a-2) + '..' + str(b + 2)
                s2 = at.recoverTargetSeqFromQuery(qseq, csstr, tmprg, da['strand'])
                """
                #sys.stderr.write('qstr ' + da['qstr'] + '_\n')
                #sys.stderr.write('tstr ' + da['tstr'] + '_\n')
                #sys.stderr.write('cdsrg_' + cds + '_\n')
                #sys.stderr.write('cdsrg_' + cdsrg + '_\n')
                #sys.stderr.write('cs_' + csstr + '_\n')
                #sys.stderr.write('s0_' + s0 + '_\n')
                #sys.stderr.write('s1_' + s1 + '_\n')
                #sys.stderr.write('s2_' + s2 + '_\n')
                """
                left = s2[0:2]
                right = s2[-2] + s2[-1]
                intronBound += left +  ":"  + right + "_"

"
I just added a condition to check whether the recovering segment is empty of not for downstream process

**Comment by xuxingyubio** [comment]
Thank you for your reply, I have modified the content above, but the following problem still occurs:
HLA-P*02:01:01:02MetGluLysGluAlaValMetLeuRrgLeuHis(ATGGAAAAGGAGGCAGTTATGCTCAGGCTTCAT)<()
Error in calling new allele : nameNewAllele

**Comment by YingZhou001** [comment]
Thanks a lot for reporting this bug, I think you may need to modify the  the function "nameNewHlaAllele" in script file "callIPDallele.py" that changing 
```python
regex = re.compile(r'(\w+)\(\w*\)<(\w+)\(\w*\)')
```
into
```python
regex = re.compile(r'(\w*)\(\w*\)<(\w*)\(\w*\)')
```
Could you let me know what kind of data you are working on? HiFi assemblies or other? Immuannot may perform weird if the assembly is in low quality or very far away from human.

**Comment by xuxingyubio** [comment]
Thank you very much, the program is now running smoothly. I assembled it based on data from next generation sequencing, so the assembly quality is relatively poor.

**Comment by YingZhou001** [comment]
I see, thanks a lot for helping me debug the program!
